```{r}
link='https://github.com/qziegler/VisualAnalytics_2_tabularData/raw/master/data_forclass/FY2017_DCCrimeData.csv'
```

```{r}
#for Stata files:
# library(foreign)
# mydata=read.dta(link)

#for CSV files:
mydata=read.csv(link)
```

```{r}
names(mydata)
```
```{r}

offenseT <- table(mydata$OFFENSE, exclude = 'nothing')
offenseTpct = prop.table(offenseT)

```

```{r}
offenseTdf = as.data.frame(offenseTpct)
names(offenseTdf) <- c("Offense", "Percent")
offenseTdf$Percent <- sapply(offenseTdf$Percent, function(x) x*100)

offenseTdf$Offense <- factor(offenseTdf$Offense, levels = offenseTdf$Offense[order(-offenseTdf$Percent)])

offenseTdf
```

```{r}
library(ggplot2)

base = ggplot(data = offenseTdf,
              aes(x = Offense,
                  y = Percent))
```

```{r}
plot1 = base + geom_bar(fill = "navy",
                        stat = "identity")

plot2 = plot1 + coord_flip()

plot3 = plot2 + labs(title = "Washington, DC 2017 - Crime by Offense Type",
                     x = "Offense Type",
                     y = "Share")

plot3

```

```{r}

plot4 = plot3 + scale_y_continuous(breaks = c(0,5,10,15,20,25,30,35,30,40,45,50),
                                   limits = c(0,50),
                                   labels = scales::unit_format(suffix = '%'))

plot5 = plot4 + theme(panel.background = element_rect(fill = "white",
                                                      color = "grey50"))

plot5

```

```{r}
plot6 = plot5 + geom_text(aes(y = Percent ,
                            label = paste0(round(Percent,2), '%')),
                        vjust=0, # if flipping 'hjust'
                        hjust=-0.25,
                        size = 2.5)

plot7 = plot6 + theme(axis.text = element_text(size = 7),
                      axis.title = element_text(size = 12),
                      title = element_text(size = 14, face = "bold"))

plot7

```

```{r}
offenseTdf$Gap=offenseTdf$Percent - 10
offenseTdf$PositiveGap=ifelse(offenseTdf$Gap>0,T,F)

base = ggplot(offenseTdf, aes(Offense,Gap,
                              color=PositiveGap,
                              label=round(Gap,3)))

lolliplot1 = base + geom_segment(aes(y = 0,
                                     x = Offense,
                                     yend = Gap,
                                     xend = Offense), color = "grey50")

lolliplot1 = lolliplot1 + geom_point()

lolliplot2 = lolliplot1 + scale_x_discrete(limits=offenseTdf$Offense)
lolliplot3 = lolliplot2 + geom_text(nudge_x = 0.3, show.legend = FALSE, size = 2.5)

lolliplot4 = lolliplot3 + coord_flip()

lolliplot4

```

```{r}

lolliplot5 = lolliplot4 + labs(title = "Washington, D.C. 2017 \nOffense Types Accounting for > 10% of All Crime",
                               x = "Offense Type",
                               y = "Gap (Percentage Points)")

lolliplot6 = lolliplot5 + theme(panel.background = element_rect(fill = "white",
                                                      color = "grey50"))

lolliplot7 = lolliplot6 + theme(title = element_text(size = 10, face = "bold"),
                                axis.text = element_text(size = 7),
                                axis.title = element_text(size = 12))

lolliplot8 = lolliplot7 + scale_y_continuous(breaks = c(-15,-10,-5,0,5,10,15,20,25,30,35,30,40,45,50),
                                   limits = c(-15,50),
                                   labels = scales::unit_format(suffix = '%'))

lolliplot9 = lolliplot8 + geom_hline(yintercept = 0, color = "grey80")

lolliplot9

```

